version: '3'
services:
  frontend:
    image: frontend
    build: ./client/
    ports:
      - "3000:3000"
    networks:
      - deploy-app
  api-server:
    image: api-server
    build: ./server/
    ports:
      - "8080:8080"
    networks:
      - deploy-app
networks:
  deploy-app:
    driver: bridge
